Traceback (most recent call last):
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/frederikwr/anaconda3/envs/WindBro/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import sys
from pathlib import Path
sys.path.append(str(Path(os.getcwd()).parent.parent))

from src.utils import (
    ElevationHandler,
    print_code,
    transform_coordinates,
    resample_to_straight_axis,
    generate_voxel_map,
    download_elevation
)

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from cartopy.io.img_tiles import GoogleTiles
import cartopy.crs as ccrs
from matplotlib.ticker import AutoLocator
from IPython.core.display import HTML
from matplotlib.colors import ListedColormap
from matplotlib.cm import ScalarMappable
import ipywidgets
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 6[0m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpathlib[39;00m [38;5;28;01mimport[39;00m Path
[1;32m      4[0m sys[38;5;241m.[39mpath[38;5;241m.[39mappend([38;5;28mstr[39m(Path(os[38;5;241m.[39mgetcwd())[38;5;241m.[39mparent[38;5;241m.[39mparent))
[0;32m----> 6[0m [38;5;28;01mfrom[39;00m [38;5;21;01msrc[39;00m[38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m (
[1;32m      7[0m     ElevationHandler,
[1;32m      8[0m     print_code,
[1;32m      9[0m     transform_coordinates,
[1;32m     10[0m     resample_to_straight_axis,
[1;32m     11[0m     generate_voxel_map,
[1;32m     12[0m     download_elevation
[1;32m     13[0m )
[1;32m     15[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m     16[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m

[0;31mModuleNotFoundError[0m: No module named 'src.utils'
ModuleNotFoundError: No module named 'src.utils'

